config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :messages, only: [:index, :new, :create]
  resources :users, param: :nickname, only: [:show, :edit, :update] do
    patch :follow
  end
  authenticated :user do 
    root 'messages#index'
  end

  unauthenticated do
    root 'static#landing', as: :landing
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/follow.rb
# frozen_string_literal: true

class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :follower, class_name: :User
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user, optional: false

  validates :content, presence: true

  after_create_commit :broadcast_message

  private

  def broadcast_message
    broadcast_prepend_to user
    user.followers.find_each { |u| broadcast_prepend_to u }
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  # Intermediate tables
  has_many :follows
  has_many :followings, foreign_key: :follower_id, class_name: :Follow

  # User relations
  has_many :followers, through: :follows
  has_many :followed, through: :followings, source: :user
  has_many :messages,  -> { order(created_at: :desc) }, dependent: :destroy

  validates :nickname, uniqueness: true, presence: true

  def follows?(user_id)
    followings.where(user_id: user_id).any?
  end

  def to_param
    nickname.to_s
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # See https://stackoverflow.com/a/42572759/4870465
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < SignedInApplicationController
  def index
    @messages = Message.where(user: current_user.followed.ids + [current_user.id])
                       .includes(:user)
                       .order(created_at: :desc)
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(permitted_params)
    @message.user = current_user

    if @message.save
      respond_to do |format|
        format.html { redirect_to messages_path }
        format.turbo_stream
      end
    else
      render 'messages/new'
    end
  end

  private

  def permitted_params
    params.require(:message).permit(:content)
  end
end

app/controllers/signed_in_application_controller.rb
# frozen_string_literal: true

class SignedInApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :fetch_recommended_users

  private

  def fetch_recommended_users
    @recommended_users = User.all.where.not(id: current_user.followed.ids + [current_user.id])
  end
end

app/controllers/static_controller.rb
# frozen_string_literal: true

class StaticController < ApplicationController
  def landing; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < SignedInApplicationController
  before_action :set_user, only: %i[edit update]

  def show
    @user = User.find_by_nickname!(params[:nickname])
  end

  def update
    @user = User.find(current_user.id)

    if @user.update(permitted_params)
      redirect_to edit_user_path(@user), notice: 'User has been updated succesfully!'
    else
      render 'users/edit', status: :unprocessable_entity
    end
  end

  def follow
    user = User.find_by_nickname(params[:user_nickname])

    if current_user.follows?(user.id)
      current_user.followings.where(user: user).destroy_all
    else
      current_user.followings.create!(user: user)
    end
    redirect_to user
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def permitted_params
    params.require(:user).permit(:nickname)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def nav_link_to(text, path)
    link_to text, path,
            class: 'group grid gap-x-2 gap-y-1 grid-cols-1 lg:grid-cols-auto-span items-center
              justify-items-center lg:justify-items-start mx-1 px-3 py-2 rounded-lg bg-transparent
              hover:bg-[#25263D] focus:bg-[#25263D] whitespace-nowrap'
  end
end

app/helpers/devise_helper.rb
# frozen_string_literal: true

# devise helper
module DeviseHelper
  def devise_error_messages!
    return if resource.errors.empty?

    messages = resource.errors.full_messages.map do |msg|
      content_tag(:p, "- #{msg}.")
    end.join
    sentence = I18n.t('errors.messages.not_saved',
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
      <div class="bg-red-100 border-l-4 border-red-500 mb-4 p-4 text-red-700" role="alert">
          <p class="font-bold">Oops!</p>
          <p>#{sentence}</p>#{messages}
      </div>
    HTML

    html.html_safe
  end

  def devise_simple_error_messages!
    return if resource.errors.empty?

    sentence = 'Ooops!'
    if resource.errors.count == 1
      message =  resource.errors.full_messages[0]
      html = <<-HTML
        <div class="bg-red-lightest border-l-4 border-red text-orange-dark p-4" role="alert">
          <p class="font-bold">#{sentence}</p>
          <p> #{message}.</p>
        </div>
      HTML
    else
      messages = resource.errors.full_messages.map do |msg|
        content_tag(:li, "#{msg}.")
      end.join
      html = <<-HTML
        <div class="bg-red-100 border-l-4 border-red-500  mb-4 p-4 text-red-700" role="alert">
          <p class="font-bold">#{sentence}</p>
          <ul class="list-disc">
            #{messages}
          </ul>
        </div>
      HTML
    end

    html.html_safe
  end
end

app/views/layouts/_navbar.html.erb
<header class="fixed top-0 z-50 w-full text-xs lg:text-sm font-semibold lg:font-medium text-white shadow bg-gray-900">
  <div class="flex justify-between items-center w-full h-16 max-w-[100rem] mx-auto px-4 sm:px-8">
    <%= link_to 'TWire', root_path%>
    <nav class="flex items-center">
        <% if user_signed_in?%>
          <%= nav_link_to 'Home', root_path %>
          <%= nav_link_to 'Profile', user_path(current_user) %>
          <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'group grid gap-x-2 gap-y-1 grid-cols-1 lg:grid-cols-auto-span items-center justify-items-center lg:justify-items-start mx-1 px-3 py-2 rounded-lg bg-transparent hover:bg-[#25263D] focus:bg-[#25263D] whitespace-nowrap' %>
        <% else %>
          <%= nav_link_to 'Sign in', new_user_session_path %>
          <%= nav_link_to 'Sign up', new_user_registration_path %>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_profile.html.erb
<div class="flex justify-between pb-4">
  <span class="flex items-center">
    <h1 class="block text-lg font-medium text-gray-700"><%= link_to user.nickname, user_path(user) %></h1>
    <% if edit && current_user.id == user.id %>
      <%= link_to '✏️', edit_user_path(current_user) %>
    <% end %>
  </span>
  <% if current_user.id != user.id %>
    <%= button_to((current_user.follows?(@user.id) ? 'Unfollow' : 'Follow'), user_follow_path(@user), method: :patch, class: 'inline-flex items-center justify-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 ml-2') %>
  <% end %>
</div>
<div class="flex justify-between">
  <div class="flex flex-col items-center">
    <strong>Followers</strong>
    <span><%= user.followers.count%></span>
  </div>
  <div class="flex flex-col items-center">
    <strong>Following</strong>
    <span><%= user.followings.count%></span>
  </div>
  <div class="flex flex-col items-center">
    <strong>Messages</strong>
    <span><%= user.messages.count%></span>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="w-full min-h-full md:grid grid-rows-auto-span grid-cols-1 text-gray-600 text-sm antialiased tracking-[-.01em] py-16 lg:pb-0">
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="w-full min-h-full md:grid grid-rows-auto-span grid-cols-1 text-gray-600 text-sm antialiased tracking-[-.01em] py-16 lg:pb-0">
    <%= render 'layouts/navbar' %>
    <div class="h-full flex flex-col justify-center items-center p-6 lg:p-10">
      <div class="w-full max-w-sm lg:w-96 mt-16 pb-16 mb-auto">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/signed_in_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="w-full min-h-full md:grid grid-rows-auto-span grid-cols-1 text-gray-600 text-sm antialiased tracking-[-.01em] py-16 lg:pb-0">
    <%= render 'layouts/navbar' %>
    <main class="grid grid-rows-auto-span">
      <div class="h-full w-full min-h-screen ">
        <div class="relative min-h-full flex flex-col">
          <div class="flex-grow w-full min-h-screen max-w:20	mx-auto xl:px-8 lg:flex">
            <div class="flex-1 min-w-0 bg-white xl:flex">
              <div class="xl:flex-shrink-0 xl:w-80 xl:border-r xl:border-gray-200 bg-white">
                <div class="pl-4 pr-6 py-6 sm:pl-6 lg:pl-8 xl:pl-0">
                  <div class="flex-1 space-y-8 py-5">
                    <div class="space-y-8 sm:justify-between sm:items-center xl:block xl:space-y-8">
                      <%= render 'layouts/profile', user: current_user, edit: true %>
                      <% if @recommended_users.any?%>
                        <h2 class="block text-lg font-medium text-gray-700">Friends you may know</h2>
                        <ul>
                          <% @recommended_users.map do |user|%>
                            <li class="block text-md font-medium text-gray-700 mb-1"><%= link_to user.nickname, user_path(user) %><li>
                          <% end %>
                        </ul>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="bg-white lg:min-w-0 lg:flex-1">
                <div class="pl-4 pr-6 pt-4 pb-4 border-b border-t border-gray-200 sm:pl-6 lg:pl-8 xl:pl-6 xl:pt-6 xl:border-t-0">
                  <%= yield %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/messages/_message.html.erb
<li class="relative pl-4 pr-6 py-5 hover:bg-gray-50 sm:py-6 sm:pl-6 lg:pl-8 xl:pl-6">
  <div class="flex items-center space-x-4">
    <div class="min-w-0 space-y-3">
      <span class="block">
        <h2><strong><%= link_to message.user.nickname, user_path(message.user) %></strong></h2>
      </span>
      
    </div>
    <div class="sm:flex flex-col flex-shrink-0 items-end space-y-3">
        <%= message.content %>
      </div>
  </div>
</li>

app/views/messages/index.html.erb
<%= turbo_stream_from current_user %>
<div class="relative pl-4 pr-6 py-5 hover:bg-gray-50 sm:py-6 sm:pl-6 lg:pl-8 xl:pl-6">
  <%= turbo_frame_tag 'new_message', src: new_message_path, target: :_top %>
</div>
<h1 class="block xl:pl-6 pl-4 sm:pl-6 text-lg font-medium text-gray-700">Feed</h1>
<ul id="messages" class="relative z-0 divide-y divide-gray-200 border-b border-gray-200">
  <%= render @messages %>
</ul>

app/views/messages/new.html.erb
<%= turbo_frame_tag 'new_message', target: :_top do %>
  <%= form_with model: @message, data: { 'controller':"new-message", 'action': 'turbo:submit-end->new-message#clearText', 'new-message-disabled-class': "bg-gray-200", 'new-message-enabled-class': "bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" } do |f|%>
    <div class="flex" >
      <%= f.text_field :content, placeholder: 'What\'s happening?', data: { 'new-message-target': 'text', 'action': 'new-message#validateInput' }, class: 'block w-full pr-3 py-2 border border-gray-300 rounded-md leading-5 bg-white placeholder-gray-500 focus:outline-none focus:placeholder-gray-400 focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm' %>
      <%= f.submit 'Share', data: { 'new-message-target': 'submit' },
      class: 'inline-flex items-center justify-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white ml-2' %>
    </div>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<% flash.each do |type, msg| %>
  <div class="w-full mb-4 rounded-xl bg-green-600 pl-5 pr-14 py-4 text-sm font-medium text-white shadow-lg">
    <%= msg %>
  </div>
<% end %>

<%= simple_form_for @user do |f|%>
  <%= f.input :nickname, required: true, input_html: { class: 'block w-full pr-3 py-2 border border-gray-300 rounded-md leading-5 bg-white placeholder-gray-500 focus:outline-none focus:placeholder-gray-400 focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm' } %>
  <%= f.submit 'Edit', class: 'inline-flex items-center justify-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 mt-4' %>
<% end %>

app/views/users/show.html.erb
<%= turbo_stream_from @user %>
<div class="relative pl-4 pr-6 py-5 hover:bg-gray-50 sm:py-6 sm:pl-6 lg:pl-8 xl:pl-6">
  <%= render 'layouts/profile', user: @user, edit: false %>
</div>
<h1 class="block xl:pl-6 pl-4 sm:pl-6 text-lg font-medium text-gray-700">Messages</h1>

<ul id="messages" class="relative z-0 divide-y divide-gray-200 border-b border-gray-200">
  <%= render @user.messages %>
</ul>